#!/bin/bash
##
# (C) Piter.NL
#
# Display X590 certificate info
#


if [ -z "$1" ] ; then
   echo "usage: <cert>"
   exit 1
fi

optInfo=1
if [ "$2" == "-cn" ] ; then 
  optCn=1
  optInfo=
fi

info() {
 if [ -n "$optInfo" ] ; then
    echo "$@"
 fi
}

parseCert() {
 local certInf="$1"
 export SUBJ=$(echo "$certInf" | grep "Subject:" | sed "s/.*Subject:[ ]*\(.*\)/\1/")
 export ISS=$(echo "$certInf" | grep "Issuer:" | sed "s/.*Issuer:[ ]*\(.*\)/\1/")
 export CN=$(echo "$certInf" | grep "Subject:" | grep CN | sed "s/.*CN[ ]*=[ ]*\([^,]*\).*/\1/g")
 export DATE=$(echo "$certInf" | grep "Not Before" | sed -e "s/.*Not.*Before[ ]*: //")
 export EXP=$(echo "$certInf" | grep "Not After" | sed -e "s/.*Not.*After[ ]*: //")
}

inf=$(openssl x509 -in "$1" -text -noout 2>/dev/null)
if [ -z "$inf" ] ; then
   inf=$(openssl x509 -inform der -in "$1" -text -noout)
fi

info "=== [x509] ==="
info "$inf"

parseCert "$inf"
if [ -n "$optInfo" ] ; then
  info  "=== [summary] ==="
  info " - SUBJECT : \"$SUBJ\""
  info " - ISSUER  : \"$ISS\""
  info " - CN      : \"$CN\""
  info " - ISSUED  : \"$DATE\""
  info " - EXPIRE  : \"$EXP\""
fi

if [ -n "$optCn" ] ; then
  echo "${CN}"
fi


