#!/bin/bash
##
# (C) Piter.NL
#
# Extract certs in p12 store to 'certs/' directory

# Arguments:
FILE="$1"
PWD="$2"

if [ -z "$PWD" ] ; then
    echo "usage: <p12> <password>"
    exit 1
fi

# Parameters:
OUT=certs
P12OUT="${OUT}/pk12certs.pems"
CERT_PREFIX=cert_

# Init
mkdir -vp "$OUT"

# openssl (+sed cleanup)
echo " - certfile : $FILE"
echo " - outdir   : $OUT"
openssl pkcs12 -nokeys -in "$FILE" -info -passin "pass:$PWD" |\
 sed -n "/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/{p}" > "$P12OUT"

# csplit: Note: first cert_00 file contains empty space:
csplit -f "$OUT/$CERT_PREFIX" -b "%02d.pem" "$P12OUT" "/----BEGIN CERTIFICATE-----/" '{*}'

rm -vf ${OUT}/${CERT_PREFIX}00.pem

# certInfo:
echo " - certs: "$(ls $OUT/*.pem)

for f in $(cd "$OUT"; ls *.pem) ; do
    BASE=$(echo $f | sed "s/.pem//")
    certInfo "$OUT/$f" > "$OUT/$BASE.txt" ;
done
